[package]
name = "restaking"
version = "0.3.1"
description = "Fragmetric Liquid Restaking Token Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "restaking"

[features]
default = []

# anchor features
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

# own features
devnet = []
mainnet = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["interface-instructions"] }
anchor-spl = "0.30.1"
bytemuck = { version = "1.17.1", features = ["derive"] }
jito-vault-sdk = { git = "https://github.com/jito-foundation/restaking.git", version = "0.0.3", tag = "v0.0.3" }
jito-vault-core = { git = "https://github.com/jito-foundation/restaking.git", version = "0.0.3", tag = "v0.0.3" }
jito-bytemuck = { git = "https://github.com/jito-foundation/restaking.git", version = "0.0.3", tag = "v0.0.3" }
base64 = "0.13.0"
shank = "0.4.2"
#pyth-solana-receiver-sdk = "0.2.0"
spl-tlv-account-resolution = "0.6.5"
spl-transfer-hook-interface = "0.6.5"
spl-stake-pool = { version = "1.0.0", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.18.15"
solana-sdk = "1.18.15"
