[package]
name = "restaking"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "restaking"

[features]
default = []

# anchor features
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

# own features
devnet = ["cpi", "idl-build"]
mainnet = ["cpi", "no-idl", "no-log-ix-name"]

[dependencies]
anchor-lang = {version = "0.30.1", features = ["init-if-needed", "interface-instructions"]}
anchor-spl = "0.30.1"
#pyth-solana-receiver-sdk = "0.2.0"
spl-tlv-account-resolution = "0.6.5"
spl-transfer-hook-interface = "0.6.5"

[dev-dependencies]
solana-program-test = "1.18.15"
solana-sdk = "1.18.15"
