[package]
name = "restaking"
version = "0.2.1"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "restaking"

[features]
default = []

# anchor features
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

# own features
devnet = []
mainnet = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["interface-instructions"] }
anchor-spl = "0.30.1"
bytemuck = { version = "1.17.1", features = ["derive"] }
#pyth-solana-receiver-sdk = "0.2.0"
spl-tlv-account-resolution = "0.6.5"
spl-transfer-hook-interface = "0.6.5"

[dev-dependencies]
solana-program-test = "1.18.15"
solana-sdk = "1.18.15"
