[package]
name = "fragmetric-util-derive"
version = "0.0.0"
edition = "2021"
description = "Provides helpful derive/attribute macros for writing fragmetric programs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.36"
syn = { version = "2", features = ["full"] }
