# credit to: https://github.com/jito-foundation/restaking/blob/master/.github/workflows/ci.yaml
#
# to test workflow locally (macOS):
#  docker pull --platform linux/amd64 ghcr.io/catthehacker/ubuntu:full-latest
# now test with:
#  act push --container-architecture linux/amd64 --platform ubuntu-latest=ghcr.io/catthehacker/ubuntu:full-latest
#  use --reuse to reuse previous container (cache might be stale)
#  use --rm --bind to totally clear previous container
#
# local container debugging
#   docker run --platform linux/amd64 --rm -it -v "$PWD":/app -w /app node:20 bash
name: fragmetric-contracts CI

env:
  RUSTUP_TOOLCHAIN_VERSION: stable
  RUSTUP_PERMIT_COPY_RENAME: 1
  SOLANA_VERSION: stable #v2.1.21
  ANCHOR_VERSION: v0.31.1
  NODE_VERSION: 20.19.0
  CI: true
  DEBUG: true
  RUNTIME: ${{(github.ref_name == 'main' || github.ref_name == 'dev' ||
    (github.event_name == 'push' && contains(github.event.head_commit.message, '[svm]')) ||
    (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[svm]'))) && 'svm' || 'litesvm' }}

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']
    paths-ignore:
      - '**/*.md'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.lock'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ github.event_name != 'workflow_dispatch' && !contains(github.event.head_commit.message, '[skip ci]') }}
    name: build and test
    runs-on: macos-latest
    #runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v4

      # setup Node runtime
      - name: setup Node $PATH
        run: |
          NODE_BIN=$(command -v node || true)
          if [ -n "$NODE_BIN" ]; then
            NODE_DIR=$(dirname "$NODE_BIN")
            echo "Detected node at: $NODE_DIR"
            echo "$NODE_DIR" >> $GITHUB_PATH
          else
            echo "Node not found, skipping PATH patch"
          fi
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          #cache-dependency-path: ./pnpm-lock.yaml

      # setup Rust and Solana runtime
      - run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUSTUP_TOOLCHAIN_VERSION }}
          components: rustfmt, clippy
          override: true
          #cache-key: ./Cargo.lock
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
          version: "0.21.2"
          locked: true
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: anchor-cli
          git: https://github.com/solana-foundation/anchor
          tag: ${{ env.ANCHOR_VERSION }}
          locked: true

      # lint Rust codes and audit dependencies
      - run: cargo audit --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2024-0344 --ignore RUSTSEC-2024-0421 --ignore RUSTSEC-2025-0022
      - run: cargo fmt --check

      # TODO: branch on target programs later
      - run: cargo clean -p restaking
      - run: cargo clippy -p restaking -- --allow warnings
      - run: cargo test-sbf -p restaking
      - run: anchor build -p restaking
      - run: pnpm build
      - name: Run integration tests
        shell: bash
        run: |
          shopt -s globstar
          files=(./programs/restaking/tests/*.test.ts)
          # run test with LiteSVM or SVM
          pnpm test "${files[@]}"

#    TODO: setup release after open-sourcing
#    if: startsWith(github.ref, 'refs/tags/v')
#    steps:
#      - uses: actions/checkout@v4
#      - run: docker pull --platform linux/amd64 solanafoundation/solana-verifiable-build:2.1.11
#      - uses: actions-rust-lang/setup-rust-toolchain@v1
#      - uses: baptiste0928/cargo-install@v3
#        with:
#          crate: solana-verify
#      - run: solana-verify build --library-name restaking --base-image solanafoundation/solana-verifiable-build:2.1.11
#      - run: ls -lh
#      - uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            target/deploy/restaking.so
#            target/idl/restaking.json
#            target/types/restaking.ts
#            clients/js/fragmetric-sdk/src/generated/restaking/* # zip it
#          fail_on_unmatched_files: true
